#!/bin/sh

# List of files to keep after upgrade.
KEEP_FILES="/etc/crypto/private_key/identity /etc/crypto/certificate/identity /etc/dropbear/dropbear_dss_host_key /etc/dropbear/dropbear_rsa_host_key"

# Location of sysupgrade archive.
SYSUPGRADE_ARCHIVE="/tmp/nodeupgrade.tgz"

if [ -z "$1" ]; then
  echo "Usage: $0 <image file or URL>"
  exit 1
fi

# Archive files.
echo "Archiving files."
TMPFILE=/tmp/nodeupgrade.files
for file in ${KEEP_FILES}; do
  echo ${file} >> ${TMPFILE}
done

rm -f "${SYSUPGRADE_ARCHIVE}"
tar cpzf "${SYSUPGRADE_ARCHIVE}" -T "${TMPFILE}" 2>/dev/null
rm -f "${TMPFILE}"

# Perform the upgrade.
echo "Doing sysupgrade."
sysupgrade -f "${SYSUPGRADE_ARCHIVE}" "$1"

